### PR TITLE
Removed ISIS3 recipe

### PR DESCRIPTION
**Pull request by jessemapel**
This is now in the main ISIS3 repo See https://github.com/USGS-Astrogeology/ISIS3/pull/650

### CODE REVIEW

**Comment by kberryUSGS** [comment]
:+1:

**Comment by kberryUSGS** [comment]
@jessemapel How will creating conda builds (as so:`./bin/build_package.py -yl isis`)  work now with the isis3 build recipe in another repo? Do we need to point to it somehow?

**Comment by jessemapel** [comment]
We'll have to use the regular conda build command line call.

We could port that script over.

I'm tempted to scrap that script because it is largely a wrapper around conda build anyway

**Comment by jessemapel** [comment]
so the following would build and run the conda-build tests but not upload:

```
conda build --no-anaconda-upload recipe
```

**Comment by kberryUSGS** [comment]
@jessemapel Sounds good! I had thought that more went into building isis3 for conda, but you're right about the script being largely a wrapper for conda build.

**Pull request merged**
